//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class image
    {
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<bool> isBlur { get; set; }
        public Nullable<bool> isClosedEye { get; set; }
        public Nullable<bool> isDark { get; set; }
        public Nullable<bool> isCutFace { get; set; }
        public Nullable<bool> isGroom { get; set; }
        public Nullable<bool> isLight { get; set; }
        public Nullable<bool> isOutdoors { get; set; }
        public Nullable<bool> isIndoors { get; set; }
        public Nullable<bool> hasChildren { get; set; }
        public Nullable<int> numPerson { get; set; }
        public Nullable<bool> isInRecycleBin { get; set; }
    }
}
